# Generated by Django 5.2.14 on 2026-06-02 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quinielas', '__first__'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField(default=0)),
                ('hit_type', models.CharField(choices=[('exact', 'Exacto'), ('goal_diff', 'Diferencia correcta'), ('winner', 'Ganador correcto'), ('miss', 'Incorrecto')], default='miss', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tournaments.match')),
                ('quiniela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quinielas.quiniela')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scoring_score',
                'unique_together': {('user', 'match', 'quiniela')},
            },
        ),
    ]
