# Generated by Django 5.2.15 on 2026-06-04 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictions', '0005_eventopartido_idx_ep_partido_quiniela_and_more'),
        ('quinielas', '0002_inscripcion_idx_inscripcion_jugador_activa_and_more'),
        ('scoring', '0004_drop_score'),
        ('tournaments', '0003_match_idx_match_tournament_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='puntuacionevento',
            index=models.Index(fields=['quiniela', 'usuario'], name='idx_pun_quiniela_usuario'),
        ),
        migrations.AddIndex(
            model_name='rankingacumulado',
            index=models.Index(fields=['quiniela', 'posicion'], name='idx_ranking_acum_quiniela_pos'),
        ),
        migrations.AddIndex(
            model_name='rankingfecha',
            index=models.Index(fields=['quiniela', 'fecha', 'posicion'], name='idx_rf_quiniela_fecha_pos'),
        ),
    ]
