# Generated by Django 5.2.15 on 2026-06-05 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_puntuacionevento_idx_pun_quiniela_usuario_and_more'),
        ('tournaments', '0003_match_idx_match_tournament_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En proceso'), ('DONE', 'Completado'), ('ERROR', 'Error')], default='PENDING', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('resumen', models.TextField(blank=True)),
                ('error_msg', models.TextField(blank=True)),
                ('fechas', models.ManyToManyField(blank=True, to='tournaments.fecha')),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job de Cálculo',
                'verbose_name_plural': 'Jobs de Cálculo',
                'db_table': 'scoring_calculo_job',
                'ordering': ['-creado_en'],
            },
        ),
    ]
