from typing import Protocol
from .entities import Group, GroupMembership
import uuid


class GroupRepositoryPort(Protocol):
    def get_by_slug(self, slug: str) -> Group | None: ...
    def get_by_invitation_code(self, code: str) -> Group | None: ...
    def save(self, group: Group) -> Group: ...
    def list_for_user(self, user_id: uuid.UUID) -> list[Group]: ...


class GroupMembershipRepositoryPort(Protocol):
    def get(self, user_id: uuid.UUID, group_id: uuid.UUID) -> GroupMembership | None: ...
    def save(self, membership: GroupMembership) -> GroupMembership: ...
    def delete(self, membership_id: uuid.UUID) -> None: ...
    def list_for_group(self, group_id: uuid.UUID) -> list[GroupMembership]: ...
