# Generated by Django 5.2.15 on 2026-06-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitationcode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invitationcode',
            index=models.Index(fields=['is_active', 'created_at'], name='idx_invitation_active_created'),
        ),
    ]
