# Generated by Django 5.2.15 on 2026-06-04 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0001_initial'),
        ('tournaments', '0003_match_idx_match_tournament_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['jugador', 'activa'], name='idx_inscripcion_jugador_activa'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['quiniela', 'activa'], name='idx_ins_quiniela_activa'),
        ),
        migrations.AddIndex(
            model_name='quiniela',
            index=models.Index(fields=['status', '-created_at'], name='idx_quiniela_status_created'),
        ),
    ]
