# Generated by Django 5.2.14 on 2026-06-01 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('external_code', models.CharField(max_length=50, unique=True)),
                ('logo_url', models.URLField(blank=True, default='')),
            ],
            options={
                'db_table': 'tournaments_team',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('external_code', models.CharField(max_length=50, unique=True)),
                ('season', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('finished', 'Finalizado')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tournaments_tournament',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('phase', models.CharField(default='group', max_length=50)),
                ('match_date', models.DateTimeField()),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En curso'), ('finished', 'Finalizado'), ('postponed', 'Postergado')], default='scheduled', max_length=20)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournaments.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournaments_match',
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tournaments', to='groups.group')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tournaments', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournaments_grouptournament',
                'unique_together': {('group', 'tournament')},
            },
        ),
    ]
