# Generated by Django 5.2.15 on 2026-06-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_fecha_match_fecha_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'match_date'], name='idx_match_tournament_date'),
        ),
    ]
