from typing import Protocol
from .entities import Notification
import uuid


class NotificationRepositoryPort(Protocol):
    def save(self, notification: Notification) -> Notification: ...
    def list_for_user(self, user_id: uuid.UUID) -> list[Notification]: ...
    def mark_read(self, notification_id: uuid.UUID) -> None: ...
    def mark_all_read(self, user_id: uuid.UUID) -> None: ...
