from typing import Protocol
from .entities import Quiniela, Inscripcion


class QuinielaRepositoryPort(Protocol):
    def get_by_slug(self, slug: str) -> Quiniela: ...
    def list_active(self) -> list[Quiniela]: ...


class InscripcionRepositoryPort(Protocol):
    def create(self, jugador_id: int, quiniela_id: int) -> Inscripcion: ...
    def deactivate(self, inscripcion_id: int) -> None: ...
    def get_by_jugador_quiniela(self, jugador_id: int, quiniela_id: int) -> Inscripcion | None: ...
    def list_by_quiniela(self, quiniela_id: int) -> list[Inscripcion]: ...
